- updated ac/am to fix build

diff --git a/kde-ac260-lt.patch b/kde-ac260-lt.patch
--- a/kde-ac260-lt.patch
+++ b/kde-ac260-lt.patch
@@ -10,3 +10,52 @@ diff -urN arts-1.5.4.org/admin/libtool.m4.in arts-1.5.4/admin/libtool.m4.in
  
    for p in `eval $output_verbose_link_cmd`; do
      case $p in
+--- libdbus-1-qt3-0.8.1/admin/cvs.sh.orig	2007-12-17 12:34:08.000000000 +0100
++++ libdbus-1-qt3-0.8.1/admin/cvs.sh	2024-11-09 22:16:38.621952395 +0100
+@@ -32,7 +32,7 @@ check_autotool_versions()
+ required_autoconf_version="2.53 or newer"
+ AUTOCONF_VERSION=`$AUTOCONF --version | head -n 1`
+ case $AUTOCONF_VERSION in
+-  Autoconf*2.5* | autoconf*2.5* | autoconf*2.6* ) : ;;
++  Autoconf*2.5* | autoconf*2.5* | autoconf*2.6* | autoconf*2.7* ) : ;;
+   "" )
+     echo "*** AUTOCONF NOT FOUND!."
+     echo "*** KDE requires autoconf $required_autoconf_version"
+@@ -47,7 +47,7 @@ esac
+ 
+ AUTOHEADER_VERSION=`$AUTOHEADER --version | head -n 1`
+ case $AUTOHEADER_VERSION in
+-  Autoconf*2.5* | autoheader*2.5* | autoheader*2.6* ) : ;;
++  Autoconf*2.5* | autoheader*2.5* | autoheader*2.6* | autoheader*2.7* ) : ;;
+   "" )
+     echo "*** AUTOHEADER NOT FOUND!."
+     echo "*** KDE requires autoheader $required_autoconf_version"
+@@ -68,7 +68,7 @@ case $AUTOMAKE_STRING in
+     echo "*** KDE requires automake $required_automake_version"
+     exit 1
+     ;;
+-  automake*1.6.* | automake*1.7* | automake*1.8* | automake*1.9* | automake*1.10*)
++  automake*1.6.* | automake*1.7* | automake*1.8* | automake*1.9* | automake*1.1[0-9]*)
+     echo "*** $AUTOMAKE_STRING found."
+     UNSERMAKE=no
+     ;;
+--- libdbus-1-qt3-0.8.1/admin/acinclude.m4.in.orig	2007-12-17 12:34:08.000000000 +0100
++++ libdbus-1-qt3-0.8.1/admin/acinclude.m4.in	2024-11-09 22:48:48.782871029 +0100
+@@ -2605,8 +2605,8 @@ AC_TRY_LINK(
+ LIBS="$ac_save_LIBS"
+ CXXFLAGS="$ac_save_CXXFLAGS"
+ AC_LANG_RESTORE
+-fi
+ ])
++fi
+ 
+ if eval "test ! \"`echo $kde_cv_qt_jpeg`\" = no"; then
+   AC_MSG_RESULT(yes)
+@@ -3472,6 +3472,7 @@ AC_DEFUN([KDE_ADD_DEPENDENCIES],
+ dnl just a wrapper to clean up configure.in
+ AC_DEFUN([KDE_PROG_LIBTOOL],
+ [
++AC_REQUIRE([AC_PROG_CC])
+ AC_REQUIRE([AC_CHECK_COMPILERS])
+ AC_REQUIRE([AC_ENABLE_SHARED])
+ AC_REQUIRE([AC_ENABLE_STATIC])
